# CDC pipeline example.
http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: "/rpcn"

input:
  http_server:
    path: /cdc

pipeline:
  processors:
    - noop: {}

output:
  stdout: {}

logger:
  level: INFO
  format: json

metrics:
  prometheus: {}
